# Generated by Django 4.2.6 on 2023-12-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_userrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
